module.exports = {
  theme: {
    backgroundColor: theme => ({
      ...theme('colors'),
      'primary-dark': '#252020',
      'secondary-dark': '#393232',
      'tertiary-dark': '#1b1616',
      'primary-light': '#f8f8ba',
      'secondary-light': '#ffffd6',
    }),
    textColor: theme => ({
      ...theme('colors'),
      'primary-dark': '#252020',
      'secondary-dark': '#393232',
      'tertiary-dark': '#1b1616',
      'primary-light': '#f8f8ba',
      'secondary-light': '#ffffd6',
    }),
    borderColor: theme => ({
      ...theme('colors'),
      'primary-dark': '#252020',
      'secondary-dark': '#393232',
      'tertiary-dark': '#1b1616',
      'primary-light': '#f8f8ba',
      'secondary-light': '#ffffd6',
    }),
  },
  variants: {
    backgroundColor: [
      'odd',
      'responsive',
      'hover',
      'focus',
      'dark',
      'dark-hover',
      'dark-focus',
      'dark-odd',
    ],
    borderColor: [
      'responsive',
      'hover',
      'focus',
      'dark',
      'dark-hover',
      'dark-focus',
    ],
    textColor: [
      'responsive',
      'hover',
      'focus',
      'group-hover',
      'focus-within',
      'dark',
      'dark-hover',
      'dark-focus',
      'dark-group-hover',
      'dark-focus-within',
    ],
  },
  plugins: [require('tailwindcss-dark-mode')()],
};
