// Generated by https://quicktype.io

export interface Action {
  action: ActionElement[];
}

export interface ActionElement {
  name: string;
  source: Source;
  page: number;
  time?: Array<TimeClass | string>;
  entries: Array<EntryClass | string>;
  isOptional?: boolean;
}

export interface EntryClass {
  type: string;
  name: string;
  entries: string[];
}

export enum Source {
  Dmg = 'DMG',
  Phb = 'PHB',
  Xge = 'XGE',
}

export interface TimeClass {
  number: number;
  unit: Unit;
}

export enum Unit {
  Action = 'action',
  Bonus = 'bonus',
  Reaction = 'reaction',
}
