// Generated by https://quicktype.io

export interface Conditions {
  condition: Condition[];
  disease: Disease[];
  status: Status[];
}

export interface Condition {
  name: string;
  source: string;
  page: number;
  srd: boolean;
  entries: Array<PurpleEntry | string>;
}

export interface PurpleEntry {
  type: Type;
  items?: string[];
  colLabels?: string[];
  colStyles?: string[];
  rows?: Array<string[]>;
}

export enum Type {
  List = 'list',
  Table = 'table',
}

export interface Disease {
  name: string;
  source: string;
  page: number;
  entries: Array<FluffyEntry | string>;
  srd?: boolean;
}

export interface FluffyEntry {
  type: string;
  entries: Array<TentacledEntry | string>;
}

export interface TentacledEntry {
  type: string;
  href: Href;
  text: string;
}

export interface Href {
  type: string;
  path: string;
  hash: string;
  hashPreEncoded: boolean;
}

export interface Status {
  name: string;
  source: string;
  page: number;
  srd: boolean;
  entries: Array<StickyEntry | string>;
}

export interface StickyEntry {
  type: Type;
  items: string[];
}
