// Generated by https://quicktype.io

export interface Language {
  language: LanguageElement[];
}

export interface LanguageElement {
  name: string;
  source: string;
  page: number;
  typicalSpeakers?: string[];
  type?: LanguageType;
  script?: string;
  srd?: boolean;
  entries?: Array<EntryClass | string>;
  additionalSources?: AdditionalSource[];
  dialects?: string[];
}

export interface AdditionalSource {
  source: string;
  page: number;
}

export interface EntryClass {
  type: EntryType;
  name: Name;
  entries: string[];
}

export enum Name {
  OptionHumanLanguages = 'Option: Human Languages',
  TheGithAlphabet = 'The Gith Alphabet',
}

export enum EntryType {
  Inset = 'inset',
}

export enum LanguageType {
  Exotic = 'exotic',
  Secret = 'secret',
  Standard = 'standard',
}
